version: '3'

services:
  base:
    build: ./container-base
    container_name: code-cooker-base
    ports:
      - 7860:7860
    tty: true
    volumes:
      - .:/root

  gpu:
    build: ./container-base
    tty: true
    volumes:
      - .:/root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
